---
apiVersion: v1
kind: Service
metadata:
  name: resourceconsist-manager
  namespace: resourceconsist
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: resourceconsist-manager