---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: resourceconsist-manager-mutating
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        namespace: resourceconsist
        name: resourceconsist-manager
        path: /mutating-generic
    failurePolicy: Fail
    name: mutating-pod.apps.kusionstack.io
    objectSelector:
      matchExpressions:
        - key: kusionstack.io/control
          operator: In
          values:
            - "true"
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - pods
          - pods/status
        scope: '*'
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: resourceconsist-manager-validating
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        namespace: resourceconsist
        name: resourceconsist-manager
        path: /validating-generic
    failurePolicy: Fail
    name: validating-pod.apps.kusionstack.io
    objectSelector:
      matchExpressions:
        - key: kusionstack.io/control
          operator: In
          values:
            - "true"
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - pods
        scope: '*'
    sideEffects: None